### ISSUE TITLE
How do you send command through GPRS protocol

### ISSUE THREAD

**Issue by NicoJuicy** [fulup-bzh/GeoGate#10]
I think this is the module ggserver.

Is there a command architecture implemented to send commands back to the device when the client is connected through the GPRS protocol?

If so, where can i extend it for other devices and learn about it's architecture?

**Comment by fulup-bzh** [comment]
Yes this is supported but not all adapter support command through GPRS. You should check https://github.com/fulup-bzh/GeoGate/blob/master/server/adapters/Gps103Tk102-adapter.js 
Method DevAdapter.prototype.SendCommand is doing this for Coban trackers.

**Comment by fulup-bzh** [comment]
Did not get any feed back I would expect that previous answer addressed your needs.
