### ISSUE TITLE
Ais: MMSI as String

### ISSUE THREAD

**Issue by afischerdev** [fulup-bzh/GeoGate#13]
In ggencoder lib the mmsi value comes as integer.
The ais definition says it is a 9-digit ID.
E.g. the base stations has 2 leading zeros.
I forgot it when I made the changes.

I did a short check for Signal K. There is no problem with the type change.
Are there other clients that come into trouble?

**Comment by fulup-bzh** [comment]
The change you made does not create trouble in GeoGate and http://sinagot.net/aisweb/mapview which is fine for me

**Comment by afischerdev** [comment]
Could you update this again please.
npm publish needs permission
Thanks

**Comment by fulup-bzh** [comment]
Done with gencoder@0.1.12

**Comment by afischerdev** [comment]
Great, thanks for that. But I didn't found the changes for string value - when I install ggencoder again. In git the change is noticed (encoder/lib/AisDecoder.js).

**Comment by fulup-bzh** [comment]
I refresh my git clone, and push back the encoder, hopefully not npm and git should be aligned.

**Comment by afischerdev** [comment]
Great, works perfect, thanks a lot.
