### ISSUE TITLE
jison dependency causing problems

### ISSUE THREAD

**Issue by tkurki** [fulup-bzh/GeoGate#30]
People are trying to create Open Embedded linux images with Signal K Node server, which uses ggencoder as you know.

OE build process for applications with npm dependencies is not 100% equal to npm process. ggencoder's jison dependency is causing problems with the build process. 

One particular problem is the mixed case package id in JSONSelect, used via jison dep in ggencoder: https://github.com/lloyd/JSONSelect/blob/master/package.json#L3. That is but one of the issues. 

Would you consider dropping the jison dependency, as it is not used by the published module and is just that bit extra, just the command line tool? You could make it a dev dependency, so that if you run `npm install` in ggencoder it would get installed, but somebody using ggencoder as a dependency would not be affected by it?

**Comment by fulup-bzh** [comment]
Effectively they is not reason to have a Jison dependency on the encoder. If you have a patch proposal to fix your problem with Open Embedded please propose it, I will be more than happy to merge it.

**Comment by mpvader** [comment]
hi @fulup-bzh see the two commits here:

https://github.com/mpvader/GeoGate/commit/cda4dfa5ca0f6df9671c19a8854aaca73d99e781

Its a small change that implements @tkurki his idea/proposal. Let me know what you think.

**Comment by mpvader** [comment]
Hm after better reading your readme I now know that ask async can be moved to the devDependencies. Sorry for that, I can change that too of course.

But first please let me know if you are OK with this devDependencies idea in general.

**Comment by fulup-bzh** [comment]
No problem for me to clean the code and remove useless dependencies. Please move forward in pushing your proposition.

**Comment by mpvader** [comment]
thanks, see pull request #31

**Comment by mpvader** [comment]
Thanks for the merge. One last request: please publish a new version to npm registry. Thank you.

**Comment by mpvader** [comment]
Bonsoir! Ping; see above request.

**Comment by fulup-bzh** [comment]
Sorry for the delay with NPM, the weather was nice and I though it was better sailing with a real boat than playing with virtual AIS target :)
Thank you for your patience.

**Comment by mpvader** [comment]
No problem; I wish I was sailing! 

Thank you; Matthijs
