### ISSUE TITLE
Some AIS feeds have talker IDs other than AI

### ISSUE THREAD

**Issue by tkurki** [fulup-bzh/GeoGate#38]
A Signal K user reported that most of the messages in AIS feed available at 153.44.253.27:5631  are ignored.

The feed's data has prefix BS
```
!BSVDM,1,1,,A,H3m=CT0tlDL4000000000000000,2*25
!BSVDM,1,1,,A,13oOBn00000NIB@SoTEcDDHN0<0H,0*38
!BSVDM,1,1,,A,33eG6N0OiOPPnC0Q49irT8RL00n0,0*4A
```

Apparently this is already fixed for BSVDM in 6eaeac6fdf513819a51fab582ecbb033e23c211c but not published to npm. Could you please publish it so that people can enjoy the fix?

Furthermore the talker does not really matter afaik, the messages are VDM and VDO, so a better check would be to just ignore the talker id and check the sentence id. I can provide a PR if you think that's the way to go.

**Comment by afischerdev** [comment]
I updated the package.json and did a publish
