### ISSUE TITLE
No support for multipart AIS message decoding

### ISSUE THREAD

**Issue by tkurki** [fulup-bzh/GeoGate#4]
Have you thought about adding support for multipart AIS message decoding?

From [comments](https://github.com/fulup-bzh/GeoGate/blob/master/encoder/lib/GG-AisDecode.js#L178) in the source file it appears that there is no support for this, but is it so that the original C++ code didn't have this either?

**Comment by fulup-bzh** [comment]
Unfortunately multipart AIS is not part of my requirement and I have no new future plan to implement it. 
Multipart would impose to handle a session when all other messages are processed stateless. I don't thing it's a huge job, but someone has to do it. Who ever is willing to propose a multipart path, I would be more than happy to merge it.

**Comment by fulup-bzh** [comment]
Done supported by decoder, still to be done for the encoder
