### ISSUE TITLE
AIS binary message decoding for weather data

### ISSUE THREAD

**Issue by KEGustafsson** [fulup-bzh/GeoGate#42]
Would it possible to add more binary message decodings to [case 8](https://github.com/fulup-bzh/GeoGate/blob/75ec4a603354f2ead0335268bcc227ae8c4d6777/encoder/lib/GG-AisDecode.js#L502)?

One interesting message could be [meteorological-hydrographic-data](https://academy.iala-aism.org/asm/meteorological-hydrographic-data/) to get weather observations from AIS where available.

**Comment by fulup-bzh** [comment]
Feel free to add it and to make a merge request. As you have a detail definition of the message, it should not be complex.

**Comment by itemir** [comment]
Interested in this, Alaska has some weather broadcasts over AIS that I would love to catch.
