### ISSUE TITLE
Checksum fails when lowercase

### ISSUE THREAD

**Issue by marcobergman** [fulup-bzh/GeoGate#46]
I don't know if nmea checksums should be uppercase, but when they are not, the checksum fails when there is a lowercase letter in it. Other software accepts lowercase checksums.

This fails checksum:
```
!AIVDM,1,1,,A,5@00050000010;7;?@0Pm>1=04pdE:340000001?<Pj??<0Ht<U2C@UBm5@000000000008,0*1f
```
This does not
```
!AIVDM,1,1,,A,5@00050000010;7;?@0Pm>1=04pdE:340000001?<Pj??<0Ht<U2C@UBm5@000000000008,0*1F
```

**Comment by fulup-bzh** [comment]
I agree they is no reason to refuse a lowercase checksum. Should not be complex to mast for uppercase the checksum before computation. If you propose a merge-request I will be more than happy to integrate it.

**Comment by marcobergman** [comment]
Ok I made the fix and tested it by making a checksum lowercase in [AisEncodeDecodeTest.js](https://github.com/fulup-bzh/GeoGate/blob/119de21c9a18a647df980e3be763213965638748/encoder/test/AisEncodeDecodeTest.js#L87); this used to create a checksum error and now its does not.
