### ISSUE TITLE
Ggencoder question about the new weather reports

### ISSUE THREAD

**Issue by afischerdev** [fulup-bzh/GeoGate#50]
This is a call for all users of this [library](https://www.npmjs.com/package/ggencoder) or this ggencoder package here:

The normal way in the library is to decode and prepare the value for output. Sample:

```
this.draught     = this.GetInt(294, 8 ) / 10.0;
```
The weather out now comes out as plain value:
```
this.airtemp       = parseInt(this.GetInt(154, 11, 1));
```
Is this ok for your or better to have a calculated value?

Please see also discussion [here](https://github.com/SignalK/nmea0183-signalk/pull/245)

**Comment by KEGustafsson** [comment]
Better would be outputting calculated value according to the specification.

**Comment by afischerdev** [comment]
Values come out now precalculated.
