### ISSUE TITLE
error SendTo Raw API Usage

### ISSUE THREAD

**Issue by muhammadbuchory** [fulup-bzh/GeoGate#7]
why this code error , GammuSms.SendTo (E:\Node Server\smsgateway\node_modules\ggsmsc\lib\GG-GammuMySql.js:163:31)?

**Comment by fulup-bzh** [comment]
I would expect this error to come because of a failing connection to MySQL, if you've checked your MySQL config, then please provide a full trace so we may get a chance to understand the error.

**Comment by muhammadbuchory** [comment]
here my config:

var SmscConfig =
       { debug   : 1            // can be overloaded with --debug in cli
       , hostname: '127.0.0.1' // Gammu MySql config
       , username: 'root'  
       , basename: 'sms'
       , password: 'root'

       , smsc    : '+6282132347212'  // your SMS gateway phone number
       , report  : true          // enforce delivery report when sending
       };

**Comment by fulup-bzh** [comment]
Only you can know if your MySQL config is good or not.  My point was that your error is related to writing the SMS request into mysql. But without the full trace I cannot understand what's happen.

**Comment by muhammadbuchory** [comment]
this is my all code:

var express = require('express');
var router = express();
var process = require('./proces.js');

var serialport = require('serialport');
var events = require('events');
var GGsmsc = require('ggsmsc').Client;
 
var sendData = '';

var emitter = new events.EventEmitter();

var SmscConfig =
       { debug   : 3            // can be overloaded with --debug in cli
       , hostname: 'localhost' // Gammu MySql config
       , username: 'root'  
       , basename: 'mmm'
       , password: ''

       , smsc    : '+6282132347212'  // your SMS gateway phone number
       , report  : true          // enforce delivery report when sending
       , delay   : 1000        // xx mseconds delay in between two check of outbox send sms table
       , retry   : 10          // number of retry before refusing removing outgoing sms MySql  queue
       };

var smsc = new GGsmsc(SmscConfig);

   function DisplayCallBack(message) {
       var count=1;
       for (var sms in message) {
           console.log(count); 
           console.log("inbox", count++, message[sms]);
       }
   };


smsc.SendTo(DisplayCallBack, '085785147593', 'This is my message');

router.get('/', function(req, res) {

  process.Dp4(req,function(status, data){
    
    res.render('index', {title :"Test", result:data});  
  })
  	
  
  serialPort.on('open',function() {
      console.log('Port open');
      });      
});


router.get('/listsms', function(req, res){

                 
     
      process.smsList(req,function(status, data){
      var params={
        title : "List SMS",
        data : data
      }
        res.render('list', params);  
      });
     
})

function listsms(req,fn){
    
  var response = '',
  timeout = 0,
  obj = {},
  arr_data = new Array(),
  readData= '',
  i=1,
  arr_data = [],
  receivedData = '';
  cleanData = '';
        setTimeout(function(){

          cmd(serialPort, 'AT+CMGF=1\r', response);
          cmd(serialPort, 'AT+CMGL="ALL"\r', response)
        },timeout); 
        timeout += 10000;
 
       
       var line = null;
       var buffer = '';
        serialPort.on('data', function(data) {
          var buffer
          // Split collected data by delimiter
          
          if (data.trim() !== '') {
            line = data;
            var parts = line.split('\r\n');           
          var arr_data = JSON.stringify({ y : parts });
          //console.log(arr_data);
          
          sendall(arr_data);
          //savedata(req, arr_data);
          }
        
      });
        
  
}


function sendall(data){
  
  CLIENTS = data;
  console.log(CLIENTS);
}

function savedata(data){
  
        var data = {
            inbox_data    : data
        };
        var query = connection.query("INSERT INTO inbox set ? ",data, function(err, rows)
        {
            if (err){
                console.log("Error inserting : %s ",err );
            }
            else{
            }
        });
        console.log(query.sql);

};



router.post('/smssend', function(req, res){
  var input = JSON.parse(JSON.stringify(req.body)),
  number = input.number,
  message = input.message,
  loop = input.looping,
  timeout=0;
  console.log(serialPort.on);
      serialPort.on('open',function() {
      console.log('Port open');
      });

      var timeout = 0;
       cmd(serialPort, 'AT\r\n', response);
       cmd(serialPort, 'AT+CMGF=1\r', response);
      for(var i = 0; i < loop ; i++){
      console.log(i)  
        var response = '';
        setTimeout(function(){
          cmd(serialPort, 'AT+CMGS="'+number+'"\r', response)
          cmd(serialPort, message, response)
          cmd(serialPort, '\x1A', response)
        },timeout); 
        timeout += 10000;
      }  
   serialPort.on('data', function(data) {
      console.log(data);
    });    
    res.redirect('/');     
});



function cmd(serial, command, response)
{
    serial.write(command, function(){
        serial.drain();
    });
}

module.exports = router;

then my problem:

![result](https://cloud.githubusercontent.com/assets/9645219/9751643/0f0db724-565c-11e5-8b34-b101aabc3244.jpg)

**Comment by fulup-bzh** [comment]
This was an error within documentation. Correct syntax is:    smsc.SendTo  (DisplayCallBack, {phone: '+xxPhonexxxNumberxxx', 'This is my message'});

Please check https://github.com/fulup-bzh/GeoGate/blob/master/smsc/bin/SendRecSms.js to get a sample.

**Comment by muhammadbuchory** [comment]
ok thank's, and i have question again, how to show  all inbox data to my webpage?

**Comment by fulup-bzh** [comment]
unfortunatly for you I do not handle webpage. You can read/write sms but when you read an SMS you remove it from the inbox, if you do not want this behaviour, I'm afraid that you will have to patch the code.

**Comment by muhammadbuchory** [comment]
siap thanks a lot.

**Comment by fulup-bzh** [comment]
you're welcome
